version: '3.8'

services:
  backend:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ..:/app  # Mount entire bodyscript directory
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      bash -c "
        apt-get update && apt-get install -y ffmpeg libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 curl &&
        pip install --upgrade pip &&
        pip install fastapi uvicorn python-multipart aiofiles mediapipe==0.10.7 opencv-python==4.8.1 pandas numpy boto3 python-dotenv psutil &&
        cd backend &&
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - backend