services:
  - type: web
    name: bodyscript-api
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_PUBLIC_DOMAIN
        value: https://pub-fe621f30af374661931e82ee5b486352.r2.dev
      - key: ADMIN_TOKEN
        generateValue: true