#!/bin/bash
echo "Testing tag functionality in index.html"
echo "Please open http://localhost:8000/index.html in your browser"
echo ""
echo "Test steps:"
echo "1. Open browser console (F12)"
echo "2. Look for debug logs with [INIT], [DATA], [RENDER], [TAG FILTER] prefixes"
echo "3. Click on any #tag to filter videos"
echo "4. Check console for filtering logs"
echo "5. Click 'Clear' button to reset filter"
echo ""
echo "Expected behavior:"
echo "- Tags should be visible under each video"
echo "- Clicking a tag should show only videos with that tag"
echo "- Console should show detailed debug logs"
echo "- Clear button should restore all videos"
echo ""
echo "Compare with working version at http://localhost:8000/test-tags.html"