services:
  - type: web
    name: bodyscript-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: R2_ACCOUNT_ID
        sync: false  # Add manually in dashboard
      - key: R2_ACCESS_KEY
        sync: false  # Add manually in dashboard
      - key: R2_SECRET_KEY
        sync: false  # Add manually in dashboard
      - key: ADMIN_TOKEN
        sync: false  # Add manually in dashboard
      - key: ENVIRONMENT
        value: production